### ISSUE TITLE
UIAppearance

### ISSUE THREAD

**Issue by gerchicov-bp** [yahoo/AppDevKit#14]
Need some info in readme about difference between this library and `UIAppearance`

**Comment by anistarsung** [comment]
@gerchicov-bp  Thanks for your suggestion but I couldn't catch your idea. Do you mind give me more information that I could improve that.

**Comment by kenobilyh** [comment]
As I known, UIAppearance can be used on customize UI in local/global scope.
Different from UIAppearance, AppDevKit make common task easier to implement, like change image color, UIColor from hex string.
These functions help you easier use on UIAppearance, like: 

```
[[UISegmentedControl appearance] setBackgroundColor:[UIColor ADKColorWithHexString:@"7A00A7"]];
```

In viewController component part, we make adjusting autolayout constraint easier, and provides pull to refresh, infinite scrolling, dynamic height cell components to make developer happier.
We also provide some [string helper](https://github.com/yahoo/AppDevKit/blob/master/AppDevPods/AppDevCommonKit/ADKStringHelper.h).

Does these answer your question?

**Comment by gerchicov-bp** [comment]
ok
