### ISSUE TITLE
ADKOpenGLImageView

### ISSUE THREAD

**Issue by moonorblue** [yahoo/AppDevKit#66]
Hi, thank you for the awesome AppDevKit.
According to the speak at MOPCON 2017 - AppDevKit x CameraKit
The **ADKOpenGLImageView** seems to be the rescue for the image rendering performance, will it be available soon ?
Thank you

**Comment by anistarsung** [comment]
Yes, it is. I am writing document and testing code for ADKOpenGLImageView. I think that it will be merged into AppDevKit in next week. Please wait few days for that. Thanks.

**Comment by anistarsung** [comment]
The PR is here: https://github.com/yahoo/AppDevKit/pull/67
Core team members will review this PR before be merged. Please be patient. Thanks.

**Comment by anistarsung** [comment]
The PR was merged.
