### ISSUE TITLE
2 category named - (void)willRemoveSubview:(UIView *)subview

### ISSUE THREAD

**Issue by cwnga2** [yahoo/AppDevKit#85]
2 category "UIScrollView+ADKInfiniteScrollingView.m" and "UIScrollView+PullToRefreshView.m"
have selector named - (void)willRemoveSubview:(UIView *)subview
it will cause one of them no be called, system will just choose 1 selector to send message

**Comment by kenobilyh** [comment]
https://github.com/yahoo/AppDevKit/pull/86 Here is my solution. Please give some advice.

**Comment by anistarsung** [comment]
The PR was merged.
